test_task:
  container:
    image: node:latest
  always:
    yarn_cache:
      folder: node_modules
      fingerprint_script: |
        cat package.json
        cat yarn.lock
      populate_script: yarn
  test_script: yarn test
